root = "."
tmp_dir = "tmp"

[build]
cmd = "go build ."
include_ext = []
exclude_dir = [".idea"]
include_dir = []
exclude_file = []
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = true

[misc]
clean_on_exit = true
